-- Create schemas
CREATE SCHEMA IF NOT EXISTS core;
CREATE SCHEMA IF NOT EXISTS virtual_office;

-- Grant permissions
GRANT ALL PRIVILEGES ON SCHEMA core TO vla_user;
GRANT ALL PRIVILEGES ON SCHEMA virtual_office TO vla_user;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA core TO vla_user;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA virtual_office TO vla_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA core GRANT ALL ON TABLES TO vla_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA virtual_office GRANT ALL ON TABLES TO vla_user;
